spring.application.name=bankapi
spring.data.mongodb.uri=mongodb+srv://ariaskenneth_db_user:J68X2Jpd6jqcwgG6@cluster0.tanqhhu.mongodb.net/bankdb
spring.data.mongodb.auto-index-creation=true
jwt.secret=QJMmWtJ/8irZoP0jG7jIjJIJ96JUGqWmj5zbY8J5SSA=
jwt.expiration-minutes=60

